### ISSUE TITLE
Critical - Endpoint http://localhost:8080/v1/ is invalid. - Error: Network Error

### ISSUE THREAD

**Issue by GabRog** [W3D3/DiffVisualizer#3]
![image](https://user-images.githubusercontent.com/37714253/54833019-9131ca00-4cbd-11e9-9127-fe18562cff68.png)
****
How to deal with this issue?
Best

**Comment by W3D3** [comment]
Hi
This application isn't supposed to be run without a backend. By default the config is pointing to a local backend, which is not running on your machine.
Depending on your goal, you could use the backend at swdyn.aau.at:8080/v1/ for Java files only.

**Comment by GabRog** [comment]
Hi,
thank you very much for your help.
I will try to run this backend, fortunately, I wanted to try diff on Java
files.

Best regards,
Gabriela


pt., 22 mar 2019, 19:19 użytkownik Christoph Wedenig <
notifications@github.com> napisał:
